---

- hosts: all
  gather_facts: no
  tasks:
    - name: Install python3-pip
      become: yes
      apt:
        force_apt_get: yes
        name: python3-pip
        cache_valid_time: 604800 # 1 week

    - name: Install python docker
      become: yes
      pip:
        name: docker
