name: main

on:
  push:
    branches:
      - 'main'

env:
  TEST_TAG: yura2201/devops-example-app:test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      - run: make compose-test-ci
      - run: make compose-lint-ci

      - name: Build and push app
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: yura2201/devops-example-app:latest

      - name: Build and push caddy
        uses: docker/build-push-action@v5
        with:
          context: .
          file: services/caddy/Dockerfile
          push: true
          tags: yura2201/devops-example-caddy:latest
