name: pull_request

on:
  - pull_request

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: make compose-build
      - run: make compose-test-ci
      - run: make compose-lint-ci
